=== AndrejMiletic/PINF2016/src/main/resources/schemas/sema_fakture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Faktura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum_izdavanja" type="xs:string"/>
                <xs:element name="Datum_valute" type="xs:string"/>
                <xs:element name="Podaci_o_izdavaocu" type="TPreduzece"/>
                <xs:element name="Podaci_o_kupcu" type="TPreduzece"/>
                <xs:element maxOccurs="unbounded" minOccurs="1" name="Stavka_fakture"
                    type="TStavkaFakture"/>
                <xs:element name="Iznos">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="15"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ukupan_rabat">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="15"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ukupna_poreska_osnova">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="15"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ukupan_PDV">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:fractionDigits value="2"/>
                            <xs:totalDigits value="15"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ukupno_za_uplatu">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="20"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" name="Dodatne_napomene" nillable="true" type="xs:string"/>
                <xs:element minOccurs="0" name="Racun_i_robu_izdao" nillable="true" type="xs:string"/>
                <xs:element minOccurs="0" name="Racun_i_robu_primio" nillable="true"
                    type="xs:string"/>
                <xs:element minOccurs="0" name="Podaci_o_prevozniku" nillable="true"
                    type="TPrevoznik"/>
            </xs:sequence>
            <xs:attribute form="unqualified" name="Broj" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="false" name="TPreduzece">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Adresa" type="xs:string"/>
            <xs:element name="Tekuci_racun" type="xs:string"/>
            <xs:element name="Maticni_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="8"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="PIB">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="9"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TStavkaFakture">
        <xs:sequence>
            <xs:element name="Sifra_robe" type="xs:string"/>
            <xs:element name="Naziv_robe" type="xs:string"/>
            <xs:element name="Jedinica_mere">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Kolicina">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Jedinicna_cena">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Rabat">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minExclusive value="-1"/>
                        <xs:maxExclusive value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Vrednost_stavke">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:totalDigits value="15"/>
                        <xs:fractionDigits value="2"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Poreska_osnovica">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:totalDigits value="15"/>
                        <xs:fractionDigits value="2"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Stopa_PDV">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                        <xs:totalDigits value="5"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Iznos_PDV">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                        <xs:totalDigits value="15"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Prodajna_vrednost">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                        <xs:totalDigits value="15"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrevoznik">
        <xs:sequence>
            <xs:element name="Naziv_prevoznika" nillable="true" type="xs:string"/>
            <xs:element name="Broj_kamiona" nillable="true" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== AndrejMiletic/PINF2016/src/main/webapp/downloads/faktura.xml
<?xml version="1.0" encoding="UTF-8"?>
<Faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/FTN/PINF/sema_fakture.xsd" Broj="umu5GDo5xN">
    <Datum_izdavanja>2017-11-03Z</Datum_izdavanja>
    <Datum_valute>2017-10-26</Datum_valute>
    <Podaci_o_izdavaocu>
        <Naziv>kfoXzsuhrL-gcaZ-66hVFSSfa.gjAR</Naziv>
        <Adresa>z82</Adresa>
        <Tekuci_racun>zePkQJPsOf4sn9GN7ZR</Tekuci_racun>
        <Maticni_broj>HbYfMirQ</Maticni_broj>
        <PIB>X9splPdsj</PIB>
    </Podaci_o_izdavaocu>
    <Podaci_o_kupcu>
        <Naziv>mo9fRb</Naziv>
        <Adresa>bPsr</Adresa>
        <Tekuci_racun>lvrRJy8sv</Tekuci_racun>
        <Maticni_broj>WcvaxGBv</Maticni_broj>
        <PIB>eSBoZU0ZN</PIB>
    </Podaci_o_kupcu>
    <Stavka_fakture>
        <Sifra_robe>Ov7</Sifra_robe>
        <Naziv_robe>FA6</Naziv_robe>
        <Jedinica_mere>H</Jedinica_mere>
        <Kolicina>600687529</Kolicina>
        <Jedinicna_cena>1323498322.93</Jedinicna_cena>
        <Rabat>85</Rabat>
        <Vrednost_stavke>1027245254.77</Vrednost_stavke>
        <Poreska_osnovica>386132406.49</Poreska_osnovica>
        <Stopa_PDV>334.12</Stopa_PDV>
        <Iznos_PDV>352104208.96</Iznos_PDV>
        <Prodajna_vrednost>1483220571.59</Prodajna_vrednost>
    </Stavka_fakture>
    <Stavka_fakture>
        <Sifra_robe>KvHkPJ</Sifra_robe>
        <Naziv_robe>fM3Fe97WhKW</Naziv_robe>
        <Jedinica_mere>Cvt</Jedinica_mere>
        <Kolicina>357278288</Kolicina>
        <Jedinicna_cena>935176521.20</Jedinicna_cena>
        <Rabat>10</Rabat>
        <Vrednost_stavke>1784843224.17</Vrednost_stavke>
        <Poreska_osnovica>1389637697.70</Poreska_osnovica>
        <Stopa_PDV>676.77</Stopa_PDV>
        <Iznos_PDV>316358944.00</Iznos_PDV>
        <Prodajna_vrednost>1168491048.41</Prodajna_vrednost>
    </Stavka_fakture>
    <Iznos>1833177254.33</Iznos>
    <Ukupan_rabat>388948908.39</Ukupan_rabat>
    <Ukupna_poreska_osnova>1041467282.43</Ukupna_poreska_osnova>
    <Ukupan_PDV>228009531.50</Ukupan_PDV>
    <Ukupno_za_uplatu>614312657.35</Ukupno_za_uplatu>
</Faktura>
